name: Ubuntu
on: [pull_request, push]
jobs:
  xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
  bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
